version: '3.9'

services:
  jpa_shop:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: jpa_shop
    ports:
      - 3306:3306

  jpa:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: jpa
    ports:
      - 3307:3306